# version: '3.8'
# COMMON__________________________________________________________________________________
x-spark-common: &spark-common
  image: bitnami/spark:4.0.0
  volumes:
    - ./spark/jobs:/opt/bitnami/spark/jobs
    # - ./jars:/opt/bitnami/spark/jars/extra
  networks:
    - stock_network


x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./spark/jobs:/opt/bitnami/spark/jobs
    # - ./jars:/opt/bitnami/spark/jars/extra
    - ./kafka:/opt/airflow/kafka
  depends_on:
    - postgres
  networks:
    - stock_network

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - stock_network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    command: "bash -c 'echo \"Waiting for Zookeeper to be healthy...\" && sleep 10 && /etc/confluent/docker/run'"
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3  # Thêm số partition mặc định
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1  # Thêm replication factor mặc định

    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - stock_network

  postgres:
      image: postgres:13
      container_name: postgres
      environment:
        POSTGRES_DB: stockdb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d stockdb"]
        interval: 5s
        timeout: 5s
        retries: 10
      networks:
      - stock_network


  # REDIS __________________________________________________________________________________
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - stock_network


  # SPARK SET UP ___________________________________________________________________________
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      SPARK_MODE: master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077


  # AIRFLOW SET UP __________________________________________________________________________
  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db migrate &&
      airflow users create --username admin --firstname admin --lastname admin --role Admin --password admin --email admin@example.com || true"

  airflow-webserver:
    <<: *airflow-common
    command: ["airflow", "webserver"]
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
  
  airflow-scheduler:
    <<: *airflow-common
    command: ["airflow", "scheduler"]
    depends_on:
      airflow-init:
        condition: service_completed_successfully
  
  airflow-worker:
    <<: *airflow-common
    command: ["airflow", "celery", "worker"]
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
  

networks:
  stock_network:
    driver: bridge
  
volumes:
  postgres_data: